CREATE TABLE EVENTREQUEST (EVENTNO VARCHAR(8) PRIMARY KEY,
DATEHELD DATE NOT NULL,
DATEREQ DATE NOT NULL,
CUSTNO VARCHAR(8) NOT NULL,
FACNO VARCHAR(8) NOT NULL,
DATEAUTH DATE,
STATUS VARCHAR(20) NOT NULL,
ESTCOST DECIMAL(15,4) NOT NULL,
ESTAUDIENCE DECIMAL(11,0) NOT NULL,
BUDNO VARCHAR(8)
);

ALTER TABLE EVENTREQUEST
ADD CHECK (STATUS IN ('Pending','Denied','Approved') ),
ADD CHECK (ESTAUDIENCE>0);
