CREATE TABLE EVENTPLANLINE (PLANNO VARCHAR(8),
LINENO INT NOT NULL,
TIMESTART DATETIME NOT NULL,
TIMEEND DATETIME NOT NULL,
NUMBERFLD INT NOT NULL,
LOCNO VARCHAR(8) NOT NULL,
RESNO VARCHAR(8) NOT NULL,
CONSTRAINT PK_Eventplanline PRIMARY KEY(PLANNO,LINENO),
CONSTRAINT FK_Planno FOREIGN KEY (PLANNO) REFERENCES EVENTPLAN (PLANNO),
CONSTRAINT FK_Locno FOREIGN KEY (LOCNO) REFERENCES LOCATION (LOCNO),
CONSTRAINT FK_Resno FOREIGN KEY (RESNO) REFERENCES RESOURCETBL (RESNO),
CHECK (TimeStart < TimeEnd)
);
